authorName: Dafna
experimentName: Dafna NNI allergy
trialConcurrency: 4
maxExecDuration: 1d
maxTrialNum: 100
trainingServicePlatform: local

# The path to Search Space
#searchSpacePath: search_space2.json
searchSpacePath: params.json
useAnnotation: false
tuner:
#  builtinTunerName: GridSearch
  builtinTunerName: TPE
# The path and the running command of trial
trial:
  command: python run_NNI.py
  codeDir: .
  gpuNum: 1
localConfig:
  # gpuIndices: 1,2
  maxTrialNumPerGpu: 1
  useActiveGpu: false